name = "interval"
defaultTargets = ["Interval"]
testDriver = "IntervalTest"


[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Interval"

[[lean_lib]]
name = "IntervalTest"
globs = ["test.+"]
leanOptions = {linter.unusedVariables = false}
